name: test-mex-with-octave

on:
  push:
    branches:
      - 'main'
  pull_request:
    # by default only opened, synchronize and reopened activity would trigger this event
    # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
    # and def on synchronize: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    branches:
      - 'main'

jobs:
  generate_code:
    runs-on: ubuntu-latest
    outputs:
      key: ${{ steps.generate-key.outputs.key}}
    steps:
    - name: Generate key
      id: generate-key
      run: |
        echo "::set-output name=key::${{ github.run_id }}-${{ github.run_attempt }}"
      shell: bash
    - uses: actions/checkout@v2
    - run: |
        mkdir tmp
        date > tmp/hello.txt
    - uses: actions/cache@v2
      env:
        cache-name: cache-generated-code
      with:
        path: tmp
        key: ${{ steps.generate-key.outputs.key }}

  compile_and_run_on_linux:
    runs-on: ubuntu-latest
    needs: generate_code
    steps:
    - uses: actions/checkout@v2
    - id: restore-cached-generated-code
      uses: actions/cache@v2
      with:
        path: tmp
        key: ${{ needs.generate_code.outputs.key }}
    - run: |
        ls
        ls tmp
        cat tmp/hello.txt
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends octave        
    - run: octave --eval "assert(3.0, 3.1, tol=1e-6)"

  compile_and_run_on_windows:
    runs-on: windows-latest
    needs: generate_code
    steps: 
    - uses: actions/checkout@v2
    - id: restore-cached-generated-code
      uses: actions/cache@v2
      with:
        path: tmp
        key: ${{ needs.generate_code.outputs.key }}
    - run: |
        ls
        ls tmp
        cat tmp/hello.txt
    - run: choco install octave.portable
    - run: octave --eval "disp(3.0*1.0)"
