name: test-mex-with-octave

on:
  push:
    branches:
      - 'main'
  pull_request:
    # by default only opened, synchronize and reopened activity would trigger this event
    # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
    # and def on synchronize: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    branches:
      - 'main'

# NOTE: we use 'artifact' instead of 'cache' because cache is OS specific, meaning we
# can't easily generate a file in linux and share it with linxu and windows via cache
jobs:
  generate_code:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.generate-artifact-name.outputs.artifact-name}}
      file-name: ${{ steps.generate-file-name.outputs.file-name}}
    steps:
      - name: Generate artifact name
        # We want to share the generated code between jobs of the same commit, but not
        # between commits, therefore we need to generate unique keys.
        id: generate-artifact-name
        run: |
          echo "::set-output name=artifact-name::codegen-${{ github.run_id }}-${{ github.run_attempt }}"
        shell: bash
      - name: Generate file name
        # We want to share the generated code between jobs of the same commit, but not
        # between commits, therefore we need to generate unique keys.
        id: generate-file-name
        run: |
          echo "::set-output name=file-name::forward"
        shell: bash        
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2  
        with:
          python-version: 3.9
          auto-update-conda: true
          environment-file: environment.yml
      - name: Generate code
        shell: bash -l {0}
        run: |
          python3 -m pip install . # use python3 here as python seems to point to python2, which is different to linux
          python3 tests/test_mex/export_model.py ${{ steps.generate-file-name.outputs.file-name}}
      - name: Store generated code and test data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.generate-artifact-name.outputs.artifact-name }}
          path: |
            ${{ steps.generate-file-name.outputs.file-name}}.c
            ${{ steps.generate-file-name.outputs.file-name}}.mat

  compile_and_run_on_linux:
    runs-on: ubuntu-latest
    needs: generate_code
    steps:
      - uses: actions/checkout@v2
      - name: Install octave
        run: |
          sudo apt -yq update
          sudo apt install -yq --no-install-recommends octave liboctave-dev        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_code.outputs.artifact-name }}
      - run: octave-cli tests/test_mex/compile_mex_and_run.m ${{ needs.generate_code.outputs.file-name }}

  compile_and_run_on_windows:
    runs-on: windows-latest
    needs: generate_code
    steps:
      - uses: actions/checkout@v2
      - name: Install octave
        run: choco install octave.portable
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_code.outputs.artifact-name }}
      # On windows, 'octave' seems to dispatch into a different process, while the
      # the current process would exist with status 0 immediately...
      - run: |
          octave-cli "tests\test_mex\compile_mex_and_run.m" ${{ needs.generate_code.outputs.file-name }}
        shell: bash
