name: test-cache-action

on:
  push:
    branches:
      - 'main'
  pull_request:
    # by default only opened, synchronize and reopened activity would trigger this event
    # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request
    # and def on synchronize: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    branches:
      - 'main'

jobs:
  test_assert_on_windows:
    runs-on: windows-latest
    steps:
      - run: |
          choco install octave.portable
          octave --eval "assert(3.0, 3.1)"
